name: mlflowtest
channels: 
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.17.3
  - pandas=0.25.3
  - jupyterlab=1.0.10 
  - scikit-learn=0.21.3
  - matplotlib=3.1.2
  - mlflow=1.4.0
  - pytorch=1.3.1
  - pytorch-cpu=1.1.0
  - torchvision=0.4.2
  - xgboost==0.90 #you can use 1.5.0 when running this in windows10, for Mac, 1.5.0 wasn't tested
